### ISSUE TITLE
Quickload directory from human3.6M missing

### ISSUE THREAD

**Issue by FilipHesse** [zhezh/adafuse-3d-human-pose#1]
Dear @zhezh,

I am following your readme to get started with AdaFuse. Specifiaclly, I want to apply it to the human3.6m dataset.

when running the evaluation command 
`python run/adafuse/adafuse_main.py --cfg experiments/h36m/h36m_4view.yaml --evaluate true`

the script tries to load the h36m_quickload_valiadation.pkl file, which I do not have:
`Traceback (most recent call last):
    
  File "run/adafuse/adafuse_main.py", line 299, in <module>
    main()
  File "run/adafuse/adafuse_main.py", line 208, in main
    normalize,
  File "/home/filip/Coding/Thesis_code/adafuse-3d-human-pose/run/adafuse/../../lib/dataset/multiview_h36m.py", line 65, in __init__
    with open(grouping_db_pickle_file, 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/filip/Documents/Thesis_local/Datasets/h36m/quickload/h36m_quickload_validation.pkl'    
`

I followed all the Install & Data Preparation steps including the ones from https://github.com/CHUNYUWANG/H36M-Toolbox (without downloading occlusion person). But it does not create a quickload directory. The only thing I changed in the h36m_4view.yaml file is the path to the dataset to my local dataset path. 

**Do I need an additional script/additional steps for preprocessing human h36m?**

My h36m directory currently contains the following directories (after creating the annot directory with the files h36m_train.pkl and h36m_validation.pkl manually to solve a previous loading error):
`.
├── annot
├── extracted
├── images
└── __pycache__

`
Thank you in advance!

**Comment by FilipHesse** [comment]
Solved this by simply creating an empty folder called quickload.

To sum up, if somebody wants to use this repository with the human3.6m dataset, then these additional steps (after following  https://github.com/CHUNYUWANG/H36M-Toolbox) should be performed:
1. rename your dataset folder to h36m
2. within the h36m dataset directory create a folder called "annot" and move the files h36m_train.pkl and h36m_validation.pkl into it
3. within the h36m dataset directory create an empty folder called "quickload"
4. modify your experiment configuration file (e.g. experiments/h36m/h36m_4view.yaml) by specifying DATASET.ROOT and changing DATDASET.DATA_FORMAT to 'jpg' (alternatively you can probably just zip the "image" directory within your h36m dataset directory
