### ISSUE TITLE
fewer views

### ISSUE THREAD

**Issue by sulei1998** [zhezh/adafuse-3d-human-pose#4]
Thanks for your code. If i want to use two views to evaluate the model, what should I do?
For example, I want to use only two views in hm3.6m dataset to evaluate. I changed the config `SELECTED_CAMS` and 'NUM_VIEWS' in 'h36m_4view.yaml' and change the dataloader like this:
![image](https://user-images.githubusercontent.com/56378342/143250918-900cd986-0a54-4453-847c-48b48203bdc3.png)
But I meet some error:
```sh
['j3d_NoFuse', 'j3d_HeuristicFuse', 'j3d_ScoreFuse', 'j3d_ransac', 'j3d_AdaFuse']
Ep:0[0/2151]    Speed 0.5 samples/s     Data 0.338s (0.338s)    Loss 0.46758 (0.46758)  Acc 0.324 (0.324)       Memory 4.54G    MPJPEs 17.4|17.2|17.5|17.4|17.5|
/opt/conda/conda-bld/pytorch_1603729128610/work/aten/src/ATen/native/cuda/Indexing.cu:658: indexSelectLargeIndex: block: [0,0,0], thread: [0,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
Traceback (most recent call last):
  File "run/adafuse/adafuse_main.py", line 299, in <module>
    main()
  File "run/adafuse/adafuse_main.py", line 273, in main
    perf_indicator = run_model(**valid_params)
  File "/root/Workspace/adafuse/run/adafuse/../../lib/core/adafuse_function.py", line 140, in run_model
    hms, extra = model(input_, **meta_, **extra_params)  # todo
  File "/root/miniconda3/envs/adafuse/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/miniconda3/envs/adafuse/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 159, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/root/miniconda3/envs/adafuse/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/Workspace/adafuse/run/adafuse/../../lib/models/adafuse_network.py", line 117, in forward
    cam_Intri_collate, cam_R_collate, cam_T_collate,
  File "/root/miniconda3/envs/adafuse/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/Workspace/adafuse/run/adafuse/../../lib/models/epipolar_fusion_layer.py", line 87, in forward
    inv_cam_Intri, inv_cam_R, inv_cam_T = get_inv_cam(cam_Intri, cam_R, cam_T)
  File "/root/Workspace/adafuse/run/adafuse/../../lib/models/epipolar_fusion_layer.py", line 52, in get_inv_cam
    return torch.inverse(intri_mat), extri_R.permute(0,2,1).contiguous(), extri_T
RuntimeError: CUDA error: device-side assert triggered
terminate called after throwing an instance of 'c10::Error'
  what():  CUDA error: device-side assert triggered
Exception raised from create_event_internal at /opt/conda/conda-bld/pytorch_1603729128610/work/c10/cuda/CUDACachingAllocator.cpp:687 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x42 (0x7faed62168b2 in /root/miniconda3/envs/adafuse/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #1: c10::cuda::CUDACachingAllocator::raw_delete(void*) + 0xad2 (0x7faed6468982 in /root/miniconda3/envs/adafuse/lib/python3.6/site-packages/torch/lib/libc10_cuda.so)
frame #2: c10::TensorImpl::release_resources() + 0x4d (0x7faed6201b7d in /root/miniconda3/envs/adafuse/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #3: <unknown function> + 0x5fb21a (0x7faf2056721a in /root/miniconda3/envs/adafuse/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #4: <unknown function> + 0x5fb2c6 (0x7faf205672c6 in /root/miniconda3/envs/adafuse/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
<omitting python frames>
frame #20: __libc_start_main + 0xf3 (0x7faf522ee0b3 in /lib/x86_64-linux-gnu/libc.so.6)

Aborted (core dumped)
```
Could you give some advice?

**Comment by zhezh** [comment]
Hi @sulei1998 , in AdaFuse, we need at least 3 views. If only two views are available, I would suggest you try VoxelPose.

**Comment by sulei1998** [comment]
Thanks for your reply!

**Comment by sulei1998** [comment]
By the way, using the method I mentioned above, I can get the result of using two views in h36m. Is this result meaningless？
![image](https://user-images.githubusercontent.com/56378342/143440671-ac644057-b086-42a9-b0e1-b4f8f7194b81.png)

**Comment by zhezh** [comment]
@sulei1998  It is meaningful for Nofuse, HeuristicFuse and ScoreFuse.
RANSAC stay same as Nofuse.
In AdaFuse, the geometry part of fusion module will take no effect, but the appearance part still works.
